### ISSUE TITLE
Invalid network set octaspace

### ISSUE THREAD

**Issue by says112** [yuriy0803/open-etc-pool-friends#101]
![Снимок экрана (381)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/4f72d0d2-d63b-4d72-91b8-e1dbfb81ece4)
The pool does not start.
![Снимок экрана (382)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/6bba5f9c-91c1-4573-a189-945da6525d11)

**Comment by yuriy0803** [comment]
Hmm

**Comment by says112** [comment]
![Снимок экрана (383)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/b1b25429-4361-4b19-9e5d-b095fc301a92)
В сети "классик" работает.
![Снимок экрана (384)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/ef9b2ca0-c6e8-4b69-9a46-b2dcf5052407)

**Comment by says112** [comment]
The "classic" network works.

**Comment by yuriy0803** [comment]
I have improved try again

**Comment by says112** [comment]
![Uploading Снимок экрана (385).png…]()

**Comment by says112** [comment]
The same thing doesn't work.

**Comment by yuriy0803** [comment]
octaspace

**Comment by yuriy0803** [comment]
I tried it and it works

**Comment by says112** [comment]
![Снимок экрана (386)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/65b4cb6b-9640-458c-8dba-3670644e71b5)
![Снимок экрана (387)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/6dff63ec-88ff-410f-9515-9248603f699c)

**Comment by says112** [comment]
Will there be no mining on the classic network?
