### ISSUE TITLE
Hello! I created my own network and coin. Tell me how can I add it to the pool?

### ISSUE THREAD

**Issue by says112** [yuriy0803/open-etc-pool-friends#107]
Hello! I created my own network and coin. Tell me how can I add it to the pool?

**Comment by yuriy0803** [comment]
You can add block reward here
https://github.com/yuriy0803/open-etc-pool-friends/blob/master/payouts/unlocker.go

**Comment by says112** [comment]
Everything is fine, I have sorted out this problem.
