### ISSUE TITLE
How i create multiple stratum

### ISSUE THREAD

**Issue by ohari5336** [yuriy0803/open-etc-pool-friends#111]
https://github.com/PowPool/ethpool/blob/1e91c48f8b800e3fc2a2e93f5fc0d5d6261d75f5/config.example.json#L50C3-L68C5
```
"stratum": {
			"enabled": true,
			"listen": "0.0.0.0:8018",
			"timeout": "300s"
		},

		"stratumVIP": {
			"enabled": false,
			"portRange": "27000-27080",
			"timeout": "300s"
		},

		"stratumTls": {
			"enabled": true,
			"listen": "0.0.0.0:18018",
			"timeout": "300s",
			"tlsCert": "certs/server.pem",
			"tlsKey": "certs/server.key"
		},
```

like this or like your new html ui

<img width="1271" alt="Screenshot 2024-01-15 at 4 19 52 PM" src="https://github.com/yuriy0803/open-etc-pool-friends/assets/22674877/25c3bc77-432b-4a18-9e75-264a5d2855de">

**Comment by ohari5336** [comment]
How i create multiple stratum? i want for nicehash, tls seperated

**Comment by yuriy0803** [comment]
https://github.com/yuriy0803/open-etc-pool-friends/tree/master/config

**Comment by ohari5336** [comment]
Ok got this, and thanks,

I more questions how I setup solo mode in pool?

**Comment by yuriy0803** [comment]
all .json "pplns": 0,

**Comment by ohari5336** [comment]
Low Worker Difficulty
One or more workers on this rig has been assigned a share/worker difficulty by your pool that is too low. Hashrate performance issues may occur.
The OPTIMAL Difficulty range for this rig is 500b - 3,000b
Please either adjust your worker settings at your pool, or change pools if you are unable to do this at your current pool. Thanks!




What I changed in config for solve this error

**Comment by ohari5336** [comment]
?
