### ISSUE TITLE
/build/env.sh Permission denied!

### ISSUE THREAD

**Issue by KaliAndriana** [yuriy0803/open-etc-pool-friends#15]
Hi buddy.
I am cuser cristianvsl (from where you have the etc pool with charts data).
Are these files private? Can't "make" as is saying permission denied!

**Comment by yuriy0803** [comment]
$ cd build

chmod 0755 env.sh

**Comment by yuriy0803** [comment]
if still not

# cd build 

# sed -i -e 's/\r$//' env.sh

# cd ..

# make 

=)
