### ISSUE TITLE
Won't build 

### ISSUE THREAD

**Issue by MiningCryptoLive** [yuriy0803/open-etc-pool-friends#22]
Git clone the project. Install all dependencies and when you try to build. Error says go mod init.

**Comment by yuriy0803** [comment]
Hello try it


$ cd build

chmod 755 env.sh

**Comment by MiningCryptoLive** [comment]
get the following error after chmod 755 env.sh

../../ethereum/go-ethereum/common/test_utils.go:27:18: undefined: os.ReadFile

**Comment by yuriy0803** [comment]
https://github.com/ethereum/go-ethereum/blob/master/common/test_utils.go

**Comment by yuriy0803** [comment]
You have problems with geth

you're doing something wrong geth

**Comment by MiningCryptoLive** [comment]
Geth is synced just fine. I will redo all and let you know how it goes

**Comment by yuriy0803** [comment]
https://github.com/etclabscore/core-geth/releases

**Comment by yuriy0803** [comment]
https://geth.ethereum.org/

**Comment by yuriy0803** [comment]
I'll do a youtube video sometime when I have time

**Comment by MiningCryptoLive** [comment]
That would be great

**Comment by MiningCryptoLive** [comment]
Finally able to get it working. Had to change go version. Thanks

**Comment by yuriy0803** [comment]
https://youtube.com/playlist?list=PLKP9goIq1Zk__N53ypgIpFCiz3uc-cq3X


I will try to make video step by step😉

**Comment by jvxis** [comment]
@MiningCryptoLive Hi, how did you exactly solve it? 
# github.com/ethereum/go-ethereum/common
../../ethereum/go-ethereum/common/test_utils.go:27:18: undefined: os.ReadFile
make: *** [Makefile:12: all] Error 2
My go version is go1.13.8 linux/amd64
thanks

**Comment by MiningCryptoLive** [comment]
> @MiningCryptoLive Hi, how did you exactly solve it? 
> # github.com/ethereum/go-ethereum/common
> ../../ethereum/go-ethereum/common/test_utils.go:27:18: undefined: os.ReadFile
> make: *** [Makefile:12: all] Error 2
> My go version is go1.13.8 linux/amd64
> thanks
> 

Make sure you chmod 755 /build/env.sh
I used go version 1.17
