### ISSUE TITLE
_

### ISSUE THREAD

**Issue by jeje0106** [yuriy0803/open-etc-pool-friends#24]
_

**Comment by yuriy0803** [comment]
Hello yes coming soon I'll make video step by step please subscribe thank you😉



https://www.youtube.com/channel/UCeSEGwWB8LWtu7BM8OpH6yA

**Comment by jeje0106** [comment]
I thank you for your help! I will follow your channel now 😉

**Comment by jeje0106** [comment]
I already have a mining pool site.. as you can see, only the personal Luck is missing.. here is my website: https://poolbe.eu. I need a bit more specific help for integration via the controller. Thanks

**Comment by MiningCryptoLive** [comment]
> Hello yes coming soon I'll make video step by step please subscribe thank you😉
> 
> https://www.youtube.com/channel/UCeSEGwWB8LWtu7BM8OpH6yA

I will follow also. Trying to start a ubiq pool. looks like your code is setup for it but if I change the network to ubiq the network stats show but the miners connected do not show and hashrate doesn't show. 

"threads": 4,
	"coin": "ubiq",
	"name": "main",
    "pplns": 9000,
	"network": "ubiq",
	"coin-name":"ubiq",

Is this the correct settings?

**Comment by yuriy0803** [comment]
Core-geth only has eth etc ubiq no longer available

**Comment by MiningCryptoLive** [comment]
> Core-geth only has eth etc ubiq no longer available

OK Thanks

**Comment by jeje0106** [comment]
if you need help with ubq i can give you advice. come chat with me on telegram. ∆∆∆

**Comment by yuriy0803** [comment]
did you test my pool ubiq?

**Comment by yuriy0803** [comment]
"network": "ubiq",

**Comment by yuriy0803** [comment]
> > Core-Geth hat nur eth etc ubiq nicht mehr verfügbar
> 
> OK danke

hast du mein pool ubiq getestet?

"Netzwerk": "ubiq",

**Comment by yuriy0803** [comment]
i'm trying to set it up

**Comment by MiningCryptoLive** [comment]
> > > Core-Geth hat nur eth etc ubiq nicht mehr verfügbar
> > 
> > OK danke
> 
> 
> have you tested my pool ubiq?
> 
> "network": "ubiq",

I tried it with network "Ubiq"

When a miner submits a share it shows a valid share and then invalid share. So it is not working for me

**Comment by yuriy0803** [comment]
> > > > Core-Geth hat nur eth etc ubiq nicht mehr verfügbar
> > > 
> > > 
> > > OK danke
> > 
> > 
> > have you tested my pool ubiq?
> > "network": "ubiq",
> 
> I tried it with network "Ubiq"
> 
> When a miner submits a share it shows a valid share and then invalid share. So it is not working for me

I'll get in touch

**Comment by yuriy0803** [comment]
> > Hello yes coming soon I'll make video step by step please subscribe thank youwink
> > https://www.youtube.com/channel/UCeSEGwWB8LWtu7BM8OpH6yA
> 
> I will follow also. Trying to start a ubiq pool. looks like your code is setup for it but if I change the network to ubiq the network stats show but the miners connected do not show and hashrate doesn't show.
> 
> "threads": 4, "coin": "ubiq", "name": "main", "pplns": 9000, "network": "ubiq", "coin-name":"ubiq",
> 
> Is this the correct settings?

Ubiq is working

You also have to create new users in Linux for ubiq geth and pool

**Comment by MiningCryptoLive** [comment]
Awesome. I will try it out tonight after work. Thanks
