### ISSUE TITLE
Compiling Frontend

### ISSUE THREAD

**Issue by jvxis** [yuriy0803/open-etc-pool-friends#25]
Hi, I'm trying to compile the front end, and I'm receiving this error.

I successfully compiled the (https://github.com/etclabscore/open-etc-pool) version, but I'm having trouble with this one. Any idea? Anything that I missed?

------------------------
node:internal/validators:173
      throw new ERR_INVALID_ARG_TYPE(name, 'Object', value);
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "options" argument must be of type object. Received an instance of Array
    at target.send (node:internal/child_process:732:7)
    at Array.forEach (<anonymous>)
    at dispatchQueuedRequests (/minera/open-etc-pool-friends/www/node_modules/workerpool/lib/WorkerHandler.js:174:21)
    at ChildProcess.<anonymous> (/minera/open-etc-pool-friends/www/node_modules/workerpool/lib/WorkerHandler.js:129:7)
    at ChildProcess.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_INVALID_ARG_TYPE'
-----------------------------

**Comment by yuriy0803** [comment]
Try deleting www and installing a new one

sudo npm install -g ember-cli@2.13
npm install -g bower
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config
npm install
bower install
./build.sh

**Comment by jvxis** [comment]
Thanks. But how can I install a new one? I need to install de open-etc-pool-friends again?

**Comment by yuriy0803** [comment]
follow my youtube channel together we will set up a pool don't forget to subscribe, best regards

https://youtube.com/playlist?list=PLKP9goIq1Zk__N53ypgIpFCiz3uc-cq3X

**Comment by jvxis** [comment]
I ran the pool, and it deleted all my files and partitions. Huge mess.

**Comment by yuriy0803** [comment]
you didn't save🤦‍♂️

**Comment by jvxis** [comment]
nothing to save, just Ubuntu and Windows OS files. But this behavior it is very unusual. How the pool Sw can damage a disk partition?

**Comment by yuriy0803** [comment]
have patience i make step by step youtube video how to set up pool properly

**Comment by yuriy0803** [comment]
It is difficult to write and explain for beginners




 best regards

**Comment by yuriy0803** [comment]
I don't know maybe today is your unlucky day

**Comment by yuriy0803** [comment]
Geth eth or etc recommended to use envm

hhd is not recommended 🧠

**Comment by jvxis** [comment]
All the best! I subscribed to your youtube channel, waiting for the video tomorrow. Maybe you can explain there.

**Comment by jvxis** [comment]
> Geth eth or etc recommended to use envm
> 
> hhd is not recommended 🧠

Just for the records. I'm using SSD (Nvme). I have a node running using core-geth in another machine (twin of this one) with the open-etc-pool

**Comment by jvxis** [comment]
It worked. The pool is running.
