### ISSUE TITLE
Payment Method

### ISSUE THREAD

**Issue by jvxis** [yuriy0803/open-etc-pool-friends#26]
Hi, Is it possible to change de payment Method to PROP in API.json?

**Comment by yuriy0803** [comment]
https://github.com/etclabscore/open-etc-pool

**Comment by jvxis** [comment]
So, for PROP, Do I need to use this other version.? This is the one I had in production, but the front end doesn't have charts. Question: If I remove, the PPLNS argument in the API.json?

**Comment by yuriy0803** [comment]
It won't work that easily.

It takes a lot of work, it's not that easy to change

And it's not just api.json

**Comment by yuriy0803** [comment]
It's coming soon for free on my youtube channel 😉

jvxis ***@***.***> schrieb am Fr., 5. Aug. 2022, 21:39:
