### ISSUE TITLE
Building Frontend Error

### ISSUE THREAD

**Issue by kennethtu0313** [yuriy0803/open-etc-pool-friends#27]
Dear Yuriy
I have got some error when I build frontend.
Could you give me some suggestion?
[https://drive.google.com/file/d/13562bzMbFnCvb9JqQhpSLZEm-KbI8YFY/view?usp=sharing](url)

node:internal/validators:164
      throw new ERR_INVALID_ARG_TYPE(name, 'Object', value);
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "options" argument must be of type object. Received an instance of Array

rsync: change_dir "/home/kenneth/pool/open-etc-pool-friends/www//dist" failed: No such file or directory (2)
rsync: mkdir "/var/www/etc2pool" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(682) [Receiver=3.1.3]

Many Thanks

**Comment by yuriy0803** [comment]
try it sudo ./build.sh

**Comment by yuriy0803** [comment]
sudo chown -R kenneth:kenneth ~/.npm 
sudo chown -R kenneth:kenneth ~/.config

**Comment by kennethtu0313** [comment]
Dear Yuriy
Thanks for your reply.
After do what you suggestion, still have error.
Please kindly take a look.
[https://drive.google.com/file/d/1qt2ag1tLkyGjMbGdS8jzrpSdvzKdTBhn/view?usp=sharing](url)
WARNING: Node v16.16.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js.
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
rsync: change_dir "/home/kenneth/pool/open-etc-pool-friends/www//dist" failed: No such file or directory (2)
node:events:505
      throw er; // Unhandled 'error' event

Many Thanks
Kenneth Tu

**Comment by yuriy0803** [comment]
cd www

ember build --environment production

**Comment by yuriy0803** [comment]
sudo npm install -g ember-cli@2.13

**Comment by yuriy0803** [comment]
v 2.13

**Comment by yuriy0803** [comment]
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs

**Comment by yuriy0803** [comment]
and then
./build.sh

**Comment by kennethtu0313** [comment]
Dear Yuriy

Thanks for reply

I check out the code again.

Here is my flow.

git clone https://github.com/yuriy0803/open-etc-pool-friends.git
cd open-etc-pool-friends
cd build
chmod 755 env.sh
cd ..
make
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo npm install -g ember-cli@2.13
sudo npm install -g bower
sudo npm install <-- I have new error here

npm ERR! code 1
npm ERR! path /home/kenneth/pool/open-etc-pool-friends/www/node_modules/ember-cli-cookie
npm ERR! command failed
npm ERR! command sh -c bower install --allow-root
npm ERR! /home/kenneth/pool/open-etc-pool-friends/www/node_modules/bower/lib/node_modules/configstore/index.js:54
npm ERR!                                throw err;
npm ERR!                                ^
npm ERR!
npm ERR! Error: EACCES: permission denied, open '/root/.config/configstore/bower-github.json'
npm ERR! You don't have access to this file.
npm ERR!

Many Thanks
Kenneth Tu

**Comment by yuriy0803** [comment]
sudo chown -R kenneth:kenneth ~/.npm
sudo chown -R kenneth:kenneth ~/.config


npm install 
bower install

**Comment by kennethtu0313** [comment]
Dear Yuriy

Still got the same error

[https://drive.google.com/file/d/1pNVnCXFacFnRhtuFKYnQ44xBg1kHq7bf/view?usp=sharing](url)

I install it at Ubuntu 20.04.4 TLS.

Could it be problem?

Many Thanks
Kenneth Tu

**Comment by kennethtu0313** [comment]
Dear Yuriy

Another question.

After I run "./build/bin/open-etc-pool-friends api.json".

I got the following error.

2022/08/07 23:27:11 Error while refreshing pending block on main: Post "http://192.168.178.30:8545": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2022/08/07 23:27:11 Error while refreshing pending block on main: Post "http://192.168.178.30:8545": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2022/08/07 23:27:13 Policy state refresh complete
2022/08/07 23:27:13 Stats collection finished 3.611435ms
2022/08/07 23:27:18 Stats collection finished 1.590225ms

Mnay Thanks
Kenneth Tu

**Comment by yuriy0803** [comment]
🤦‍♂️

**Comment by yuriy0803** [comment]
Video is coming soon on YouTube it's not easy to explain everything like that

**Comment by kennethtu0313** [comment]
Dear Yuriy

Looking forward your video

Many Thanks
Kenneth Tu

**Comment by yuriy0803** [comment]
https://youtube.com/channel/UCeSEGwWB8LWtu7BM8OpH6yA

**Comment by kennethtu0313** [comment]
Dear Yuriy

Thanks for your reply.

I already check your "open-ethereum-pool & open-ethereumclassic-pool install # Part 1 & Part 2".

Many Thanks
Kenneth Tu

**Comment by yuriy0803** [comment]
There are more videos coming, I'm not finished yet

**Comment by MiningCryptoLive** [comment]
> Dear Yuriy
> 
> Thanks for your reply.
> 
> I already check your "open-ethereum-pool & open-ethereumclassic-pool install # Part 1 & Part 2".
> 
> Many Thanks
> Kenneth Tu

Kenneth, if you still need help message me on discord and I can help you. https://discord.gg/twkSyKZBNh

**Comment by MiningCryptoLive** [comment]
> Dear Yuriy
> 
> Another question.
> 
> After I run "./build/bin/open-etc-pool-friends api.json".
> 
> I got the following error.
> 
> 2022/08/07 23:27:11 Error while refreshing pending block on main: Post "http://192.168.178.30:8545": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
> 2022/08/07 23:27:11 Error while refreshing pending block on main: Post "http://192.168.178.30:8545": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
> 2022/08/07 23:27:13 Policy state refresh complete
> 2022/08/07 23:27:13 Stats collection finished 3.611435ms
> 2022/08/07 23:27:18 Stats collection finished 1.590225ms
> 
> Mnay Thanks
> Kenneth Tu

You need to change the up address 192.168.178.30:8545 to your servers ip.
