### ISSUE TITLE
Question on adding other algorithm

### ISSUE THREAD

**Issue by MiningCryptoLive** [yuriy0803/open-etc-pool-friends#28]
Is there a way to add different algorithms? namely ergo. I would like all my pools to have the same frontend design.

**Comment by yuriy0803** [comment]
where did you get ergo pool from?

**Comment by MiningCryptoLive** [comment]
Right now I am using miningcore

**Comment by yuriy0803** [comment]
but you could do a lot of work you have to change www api entire pool

**Comment by MiningCryptoLive** [comment]
> but you could do a lot of work you have to change www api entire pool

OK that's what I thought. I will try doing something else.

**Comment by yuriy0803** [comment]
https://github.com/yuriy0803/ergoPool?organization=yuriy0803&organization=yuriy0803

**Comment by yuriy0803** [comment]
it was not finished
=(
