### ISSUE TITLE
API Down Problem

### ISSUE THREAD

**Issue by ahonder** [yuriy0803/open-etc-pool-friends#29]
Hi, 
nginx edited like;
```
# Default server configuration
# nginx example

upstream api {
    server 127.0.0.1:8080;
}

server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        root /var/www/etc2pool;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }
 location /api {
            proxy_pass http://api;
        }

        # pass PHP scripts to FastCGI server
        #
        #location ~ \.php$ {
        #       include snippets/fastcgi-php.conf;
        #
        #       # With php-fpm (or other unix sockets):
        #       fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        #       # With php-cgi (or other tcp sockets):
        #       fastcgi_pass 127.0.0.1:9000;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #       deny all;
        #}
}
```
and also running api service but frontend showing Stats API Temporarily Down.
pool service working tested with gminer,t-rex and with phoenix not connecting (tested default and -proto 1 -proto 2 -proto 3 -proto 4)

how can i solve mainly api problem?

**Comment by yuriy0803** [comment]
# Default server configuration
# nginx example

upstream api {
    server 127.0.0.1:8080;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /home/<your-user-name>/www;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
            # First attempt to serve request as file, then
            # as directory, then fall back to displaying a 404.
            try_files $uri $uri/ =404;
    }

    location /api {
            proxy_pass http://api;
    }

}


$ sudo service nginx restart


ahonder ***@***.***> schrieb am Sa., 13. Aug. 2022, 11:45:

**Comment by ahonder** [comment]
already restarted nginx service many times, not solved

**Comment by yuriy0803** [comment]
check over api.json and https://github.com/yuriy0803/open-etc-pool-friends/blob/master/www/config/environment.js

**Comment by yuriy0803** [comment]
https://github.com/yuriy0803/open-etc-pool-friends/blob/master/api.json

**Comment by yuriy0803** [comment]
If your ufw is active, enable port 80, 443, and stratum port

**Comment by yuriy0803** [comment]
https://github.com/yuriy0803/open-etc-pool-friends/blob/master/api.json#L26

**Comment by ahonder** [comment]
> check over api.json and https://github.com/yuriy0803/open-etc-pool-friends/blob/master/www/config/environment.js

api url is static public ip(is that wrong) may change to localhost or 127.0.0.1? , 80 and 443 ports enabled

**Comment by yuriy0803** [comment]
yes 127.0.0.1

**Comment by yuriy0803** [comment]
> > Überprüfen Sie api.json und https://github.com/yuriy0803/open-etc-pool-friends/blob/master/www/config/environment.js
> 
> API-URL ist statische öffentliche IP (ist das falsch) kann sich in localhost oder 127.0.0.1 ändern? , 80 und 443 Ports aktiviert

should be ip server

**Comment by ahonder** [comment]
and then rebuild front page after the api ip change right?

**Comment by yuriy0803** [comment]
{
	"threads": 4,
	"coin": "etc",
	"name": "main",
        "pplns": 9000,
	"network": "classic",
	"coin-name":"etc",

	"proxy": {
		"enabled": true,
		"listen": "0.0.0.0:8888",
		"limitHeadersSize": 1024,
		"limitBodySize": 256,
		"behindReverseProxy": false,
		"blockRefreshInterval": "120ms",
		"stateUpdateInterval": "3s",
		"difficulty": 2000000000,
		"hashrateExpiration": "3h",

		"healthCheck": true,
		"debug": true,
		"maxFails": 100,

		"stratum": {
			"enabled": true,
			"listen": "0.0.0.0:8008",
			"timeout": "120s",
			"maxConn": 8192
		},

		"policy": {
			"workers": 8,
			"resetInterval": "60m",
			"refreshInterval": "1m",

			"banning": {
				"enabled": false,
				"ipset": "blacklist",
				"timeout": 1800,
				"invalidPercent": 30,
				"checkThreshold": 30,
				"malformedLimit": 5
			},
			"limits": {
				"enabled": false,
				"limit": 30,
				"grace": "5m",
				"limitJump": 10
			}
		}
	},

	"api": {
		"enabled": true,
		"purgeOnly": false,
		"purgeInterval": "10m",
		"listen": "0.0.0.0:8080",
		"statsCollectInterval": "5s",
		"hashrateWindow": "30m",
		"hashrateLargeWindow": "3h",
		"luckWindow": [64, 128, 256],
		"payments": 30,
		"blocks": 50,
		"poolCharts":"*/20 * * * *",
		"poolChartsNum":74,
		"minerCharts":"*/20 * * * *",
                "minerChartsNum":74,
                "netCharts":"*/20 * * * *",
                "netChartsNum":74,
                "shareCharts":"*/20 * * * *",
                "shareChartsNum":74
	},

	"upstreamCheckInterval": "5s",
	"upstream": [
		{
			"name": "main",
			"url": "http://127.0.0.1:8545",
			"timeout": "10s"
		},
		{
			"name": "backup",
			"url": "http://127.0.0.2:8545",
			"timeout": "10s"
		}
	],

	"redis": {
		"endpoint": "127.0.0.1:6379",
		"poolSize": 10,
		"database": 0,
		"password": ""
	},
  
	"exchange": {
		   "enabled": true,
		   "url": "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=ethereum-classic",
		   "timeout": "50s",
		   "refreshInterval": "900s"
    },

	"unlocker": {
		"enabled": true,
		"poolFee": 1.0,
		"poolFeeAddress": "",
		"depth": 120,
		"immatureDepth": 20,
		"keepTxFees": false,
		"interval": "10m",
		"daemon": "http://127.0.0.1:8545",
		"timeout": "10s"
	},

	"payouts": {
		"enabled": false,
		"requirePeers": 1,
		"interval": "20m",
		"daemon": "http://127.0.0.1:8545",
		"timeout": "10s",
		"address": "0x9dd0226060b6d9644066029f4993CB2A40cF775D",
		"gas": "21000",
		"gasPrice": "50000000000",
		"autoGas": true,
		"threshold": 500000000,
		"bgsave": false,
		"concurrentTx": 10
	},

	"newrelicEnabled": false,
	"newrelicName": "MyEtherProxy",
	"newrelicKey": "SECRET_KEY",
	"newrelicVerbose": false
}

**Comment by yuriy0803** [comment]
only changes wallet address

**Comment by yuriy0803** [comment]
https://github.com/yuriy0803/open-etc-pool-friends/blob/master/www/config/environment.js#L18
https://github.com/yuriy0803/open-etc-pool-friends/blob/master/www/config/environment.js#L21
https://github.com/yuriy0803/open-etc-pool-friends/blob/master/www/config/environment.js#L25
should be ip server
and 
./build.sh

**Comment by ahonder** [comment]
thanks, it worked
