### ISSUE TITLE
Running Pool Error - util: Can't parse duration ``: time: invalid duration ""

### ISSUE THREAD

**Issue by jvxis** [yuriy0803/open-etc-pool-friends#30]
Hi @yuriy0803 Running the Pool I'm getting this error now.

2022/08/15 09:54:51 Loading config: /friendspool/open-etc-pool-friends/api.json
2022/08/15 09:54:51 Running with 10 threads
2022/08/15 09:54:51 Backend check reply: PONG
2022/08/15 09:54:51 Set Exchange data refresh every 15m0s
2022/08/15 09:54:51 &{GET https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=ethereum-classic HTTP/1.1 1 1 map[Accept:[application/json] Content-Type:[application/json]] <nil> <nil> 0 [] false api.coingecko.com map[] map[] <nil> map[]   <nil> <nil> <nil> 0xc0000280d0}
2022/08/15 09:54:51 Starting API on 0.0.0.0:8080
2022/08/15 09:54:51 Set stats collect interval to 5s
2022/08/15 09:54:51 Set purge interval to 10m0s
2022/08/15 09:54:51 Purged stale stats from backend, 0 shares affected, elapsed time 360.641µs
2022/08/15 09:54:51 Policy state refresh complete
2022/08/15 09:54:51 Set policy stats reset every 1h0m0s
2022/08/15 09:54:51 Set policy state refresh every 1m0s
2022/08/15 09:54:51 Running with 8 policy workers
2022/08/15 09:54:51 Upstream: main => http://192.168.19.11:8545
2022/08/15 09:54:51 Upstream: backup => http://192.168.19.11:8545
2022/08/15 09:54:51 Default upstream: main => http://192.168.19.11:8545
panic: util: Can't parse duration ``: time: invalid duration ""

goroutine 43 [running]:
github.com/yuriy0803/open-etc-pool-friends/util.MustParseDuration({0x0, 0x0})
        /friendspool/open-etc-pool-friends/build/_workspace/src/github.com/yuriy0803/open-etc-pool-friends/util/util.go:73 +0x85
github.com/yuriy0803/open-etc-pool-friends/proxy.(*ProxyServer).ListenTCP(0xc00032c000)
        /friendspool/open-etc-pool-friends/build/_workspace/src/github.com/yuriy0803/open-etc-pool-friends/proxy/stratum.go:21 +0x65
created by github.com/yuriy0803/open-etc-pool-friends/proxy.NewProxy
        /friendspool/open-etc-pool-friends/build/_workspace/src/github.com/yuriy0803/open-etc-pool-friends/proxy/proxy.go:68 +0x2e7

**Comment by yuriy0803** [comment]
i need more information

Have you reinstalled pool and the blocks is already there. What does your api.json look like?

**Comment by yuriy0803** [comment]
If I add new code you might have to reset the pool
If you got blocks

**Comment by yuriy0803** [comment]
Where did you install geth and pool in the same server?

**Comment by jvxis** [comment]
Geth is installed and running in a machine 192.168.19.11 / pool is installed in 192.168.19.12. I install the open-etc-pool sw in another machine and it running ok. The problem is when I try to run the open-etc-pool-friend. 
{
	"threads": 10,
	"coin": "etc",
	"name": "main",
        "pplns": 9000,
	"network": "classic",
	"coin-name":"etc",

	"proxy": {
		"enabled": true,
		"listen": "0.0.0.0:8888",
		"limitHeadersSize": 1024,
		"limitBodySize": 256,
		"behindReverseProxy": false,
		"blockRefreshInterval": "120ms",
		"stateUpdateInterval": "3s",
		"difficulty": 2000000000,
		"hashrateExpiration": "3h",

		"healthCheck": true,
		"debug": true,
		"maxFails": 100,

		"stratum": {
			"enabled": true,
			"listen": "0.0.0.0:8008",
			"maxConn": 8192,
			"tls": false,
                        "certFile": "/path/to/cert.pem",
                        "keyFile": "/path/to/key.pem"
		},

		"policy": {
			"workers": 8,
			"resetInterval": "60m",
			"refreshInterval": "1m",

			"banning": {
				"enabled": false,
				"ipset": "blacklist",
				"timeout": 1800,
				"invalidPercent": 30,
				"checkThreshold": 30,
				"malformedLimit": 5
			},
			"limits": {
				"enabled": false,
				"limit": 30,
				"grace": "5m",
				"limitJump": 10
			}
		}
	},

	"api": {
		"enabled": true,
		"purgeOnly": false,
		"purgeInterval": "10m",
		"listen": "0.0.0.0:8080",
		"statsCollectInterval": "5s",
		"hashrateWindow": "30m",
		"hashrateLargeWindow": "3h",
		"luckWindow": [64, 128, 256],
		"payments": 30,
		"blocks": 50,
		"poolCharts":"*/20 * * * *",
		"poolChartsNum":74,
		"minerCharts":"*/20 * * * *",
                "minerChartsNum":74,
                "netCharts":"*/20 * * * *",
                "netChartsNum":74,
                "shareCharts":"*/20 * * * *",
                "shareChartsNum":74
	},

	"upstreamCheckInterval": "5s",
	"upstream": [
		{
			"name": "main",
			"url": "http://192.168.19.11:8545",
			"timeout": "10s"
		},
		{
			"name": "backup",
			"url": "http://192.168.19.11:8545",
			"timeout": "10s"
		}
	],

	"redis": {
		"endpoint": "127.0.0.1:6379",
		"poolSize": 10,
		"database": 0,
		"password": ""
	},
  
	"exchange": {
		   "enabled": true,
		   "url": "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=ethereum-classic",
		   "timeout": "50s",
		   "refreshInterval": "900s"
    },

	"unlocker": {
		"enabled": false,
		"poolFee": 1.0,
		"poolFeeAddress": "",
		"depth": 120,
		"immatureDepth": 20,
		"keepTxFees": false,
		"interval": "10m",
		"daemon": "http://192.168.19.11:8545",
		"timeout": "10s"
	},

	"payouts": {
		"enabled": false,
		"requirePeers": 25,
		"interval": "20m",
		"daemon": "http://192.168.19.11:8545",
		"timeout": "10s",
		"address": "0x503B03fAF04f855199247C1a8D627D286792058f",
		"gas": "21000",
		"gasPrice": "50000000000",
		"autoGas": true,
		"threshold": 500000000,
		"bgsave": false,
		"concurrentTx": 10
	},

	"newrelicEnabled": false,
	"newrelicName": "MyEtherProxy",
	"newrelicKey": "SECRET_KEY",
	"newrelicVerbose": false
}

**Comment by yuriy0803** [comment]
https://github.com/yuriy0803/open-etc-pool-friends/blob/master/api.json#L93

Attempt to change to 1 or 5 database

**Comment by yuriy0803** [comment]
And don't forget to enable port in ufw if ufw is enabled 8545 8008

**Comment by jvxis** [comment]
same error:
oot@friendsubuntu18:/friendspool/open-etc-pool-friends# ./build/bin/open-etc-pool-friends api.json
2022/08/15 11:30:34 Loading config: /friendspool/open-etc-pool-friends/api.json
2022/08/15 11:30:34 Running with 10 threads
2022/08/15 11:30:34 Backend check reply: PONG
2022/08/15 11:30:34 Starting API on 0.0.0.0:8080
2022/08/15 11:30:34 Set stats collect interval to 5s
2022/08/15 11:30:34 Set purge interval to 10m0s
2022/08/15 11:30:34 Set Exchange data refresh every 15m0s
2022/08/15 11:30:34 &{GET https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=ethereum-classic HTTP/1.1 1 1 map[Accept:[application/json] Content-Type:[application/json]] <nil> <nil> 0 [] false api.coingecko.com map[] map[] <nil> map[]   <nil> <nil> <nil> 0xc0000280d0}
2022/08/15 11:30:34 Purged stale stats from backend, 0 shares affected, elapsed time 722.244µs
2022/08/15 11:30:34 Policy state refresh complete
2022/08/15 11:30:34 Set policy stats reset every 1h0m0s
2022/08/15 11:30:34 Set policy state refresh every 1m0s
2022/08/15 11:30:34 Running with 8 policy workers
2022/08/15 11:30:34 Upstream: main => http://192.168.19.11:8545
2022/08/15 11:30:34 Upstream: backup => http://192.168.19.11:8545
2022/08/15 11:30:34 Default upstream: main => http://192.168.19.11:8545
panic: util: Can't parse duration ``: time: invalid duration ""

**Comment by yuriy0803** [comment]
How did you geth config?

**Comment by yuriy0803** [comment]
geth --datadir /home/pool/classic/.ethereum/ --syncmode "snap" --http --http.api eth,net,web3,txpool,miner --miner.etherbase=0x95f296f317E8E3AFb3DEf009173E77cCe00B5aeC--mine --cache=8000 --maxpeers 100 --password="/home/pool/.pw" --allow-insecure-unlock --http.port "8545" --nat "any" --unlock 0x95f296f317E8E3AFb3DEf009173E77cCe00B5aeC --miner.extradata ys --classic --snapshot=false --port 30305

**Comment by jvxis** [comment]
Geth is running ok, and as I mentioned working with open-etc-pool. This the GETH command line: geth --keystore /friendspool/gethdata --datadir /friendspool/gethdata --classic --cache=21000 --txpool.globalslots=1000 --miner.etherbase="0x503B03fAF04f855199247C1a8D627D286792058f" --allow-insecure-unlock --http --http.port=8545 --http.api=eth,net,web3,miner --ws --ws.port=8546 --ws.api=eth,net,web3,miner --mine --miner.extradata='FriendsPool' --nat "extip:[177.75.4.29](http://177.75.4.29/)" --snapshot=false

**Comment by yuriy0803** [comment]
Are you sure that server port 192.168.19.11:8545 is open

**Comment by jvxis** [comment]
yes. no firewall was installed. The machines are in the same network

**Comment by yuriy0803** [comment]
"upstreamCheckInterval": "5s", "upstream": [ 	{ 		"name": "main", 		"url": "http://192.168.19.12:8545", 		"timeout": "10s" 	}, 	{ 		"name": "backup", 		"url": "http://192.168.19.11:8545", 		"timeout": "10s" 	} ],

**Comment by yuriy0803** [comment]
🤦‍♂️

**Comment by jvxis** [comment]
upstream is the server that I installed the pool sw ? or the server with the geth node?

**Comment by yuriy0803** [comment]
👍

**Comment by jvxis** [comment]
Yes, the pool is running. etc.friendspool.net

**Comment by yuriy0803** [comment]
stop your pool everything and start my pool

**Comment by yuriy0803** [comment]
it is your pool api.json

**Comment by yuriy0803** [comment]
if you install a second pool you have to change several ports except 8545

**Comment by yuriy0803** [comment]
also nginx

**Comment by jvxis** [comment]
Ok. I will try. Thanks.

**Comment by yuriy0803** [comment]
I think they connect both pools at the same time, that doesn't work

**Comment by yuriy0803** [comment]
It's not that easy to write and explain, just try turning your pool off and turning on my pool and see if there's an error

**Comment by jvxis** [comment]
maybe, I installed it on another machine. But, in this one, I ran one, stopped it, and ran your pool sw. It worked. Now I'm trying to use the same geth note, but keeping the other pool sw running.

**Comment by yuriy0803** [comment]
when i'm home show you how to add second pool


jvxis ***@***.***> schrieb am Mo., 15. Aug. 2022, 17:34:

**Comment by yuriy0803** [comment]
please send me your pool api.json


Yuriy Sh ***@***.***> schrieb am Mo., 15. Aug. 2022, 19:59:

**Comment by jvxis** [comment]
Hi @yuriy0803 , to test. I installed a new geth node on the same machine, when the sync finished, I tried again and get the same error. Then, I upgraded to 22.04, same error again. Here is my api.json:
{
	"threads": 10,
	"coin": "etc",
	"name": "main",
        "pplns": 9000,
	"network": "classic",
	"coin-name":"etc",

	"proxy": {
		"enabled": true,
		"listen": "0.0.0.0:8888",
		"limitHeadersSize": 1024,
		"limitBodySize": 256,
		"behindReverseProxy": false,
		"blockRefreshInterval": "120ms",
		"stateUpdateInterval": "3s",
		"difficulty": 2000000000,
		"hashrateExpiration": "3h",

		"healthCheck": true,
		"debug": true,
		"maxFails": 100,

		"stratum": {
			"enabled": true,
			"listen": "0.0.0.0:8008",
			"maxConn": 8192,
			"tls": false,
                        "certFile": "/path/to/cert.pem",
                        "keyFile": "/path/to/key.pem"
		},

		"policy": {
			"workers": 8,
			"resetInterval": "60m",
			"refreshInterval": "1m",

			"banning": {
				"enabled": false,
				"ipset": "blacklist",
				"timeout": 1800,
				"invalidPercent": 30,
				"checkThreshold": 30,
				"malformedLimit": 5
			},
			"limits": {
				"enabled": false,
				"limit": 30,
				"grace": "5m",
				"limitJump": 10
			}
		}
	},

	"api": {
		"enabled": true,
		"purgeOnly": false,
		"purgeInterval": "10m",
		"listen": "0.0.0.0:8080",
		"statsCollectInterval": "5s",
		"hashrateWindow": "30m",
		"hashrateLargeWindow": "3h",
		"luckWindow": [64, 128, 256],
		"payments": 30,
		"blocks": 50,
		"poolCharts":"*/20 * * * *",
		"poolChartsNum":74,
		"minerCharts":"*/20 * * * *",
                "minerChartsNum":74,
                "netCharts":"*/20 * * * *",
                "netChartsNum":74,
                "shareCharts":"*/20 * * * *",
                "shareChartsNum":74
	},

	"upstreamCheckInterval": "5s",
	"upstream": [
		{
			"name": "main",
			"url": "http://127.0.0.1:8545",
			"timeout": "10s"
		},
		{
			"name": "backup",
			"url": "http://127.0.0.1:8545",
			"timeout": "10s"
		}
	],

	"redis": {
		"endpoint": "127.0.0.1:6379",
		"poolSize": 10,
		"database": 0,
		"password": ""
	},
  
	"exchange": {
		   "enabled": true,
		   "url": "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=ethereum-classic",
		   "timeout": "50s",
		   "refreshInterval": "900s"
    },

	"unlocker": {
		"enabled": false,
		"poolFee": 1.0,
		"poolFeeAddress": "",
		"depth": 120,
		"immatureDepth": 20,
		"keepTxFees": false,
		"interval": "10m",
		"daemon": "http://127.0.0.1:8545",
		"timeout": "10s"
	},

	"payouts": {
		"enabled": false,
		"requirePeers": 1,
		"interval": "20m",
		"daemon": "http://127.0.0.1:8545",
		"timeout": "10s",
		"address": "0xdb4166bC182595067e8392Df0f46FA9f4cc87524",
		"gas": "21000",
		"gasPrice": "50000000000",
		"autoGas": true,
		"threshold": 500000000,
		"bgsave": false,
		"concurrentTx": 10
	},

	"newrelicEnabled": false,
	"newrelicName": "MyEtherProxy",
	"newrelicKey": "SECRET_KEY",
	"newrelicVerbose": false
}

**Comment by yuriy0803** [comment]
they still use the same database

"redis": {
	"endpoint": "127.0.0.1:6379",
	"poolSize": 10,
	"database": 0,
	"password": ""
},

**Comment by yuriy0803** [comment]
new pool


"redis": {
	"endpoint": "127.0.0.1:6379",
	"poolSize": 10,
	"database": 1,
	"password": ""
},

**Comment by jvxis** [comment]
different machines.  I installed everything on a new machine to test. New geth, new redis, new nginx.

**Comment by jvxis** [comment]
I also tested different database numbers

**Comment by yuriy0803** [comment]
add new pool

{
"threads": 10,
"coin": "etc2",
"name": "main",
"pplns": 9000,
"network": "classic",
"coin-name":"etc",

	"proxy": {
		"enabled": true,
		"listen": "0.0.0.0:8889",
		"limitHeadersSize": 1024,
		"limitBodySize": 256,
		"behindReverseProxy": false,
		"blockRefreshInterval": "120ms",
		"stateUpdateInterval": "3s",
		"difficulty": 2000000000,
		"hashrateExpiration": "3h",

		"healthCheck": true,
		"debug": true,
		"maxFails": 100,

		"stratum": {
			"enabled": true,
			"listen": "0.0.0.0:8009",
			"maxConn": 8192,
			"tls": false,
                        "certFile": "/path/to/cert.pem",
                        "keyFile": "/path/to/key.pem"
		},

		"policy": {
			"workers": 8,
			"resetInterval": "60m",
			"refreshInterval": "1m",

			"banning": {
				"enabled": false,
				"ipset": "blacklist",
				"timeout": 1800,
				"invalidPercent": 30,
				"checkThreshold": 30,
				"malformedLimit": 5
			},
			"limits": {
				"enabled": false,
				"limit": 30,
				"grace": "5m",
				"limitJump": 10
			}
		}
	},

	"api": {
		"enabled": true,
		"purgeOnly": false,
		"purgeInterval": "10m",
		"listen": "0.0.0.0:8081",
		"statsCollectInterval": "5s",
		"hashrateWindow": "30m",
		"hashrateLargeWindow": "3h",
		"luckWindow": [64, 128, 256],
		"payments": 30,
		"blocks": 50,
		"poolCharts":"*/20 * * * *",
		"poolChartsNum":74,
		"minerCharts":"*/20 * * * *",
                "minerChartsNum":74,
                "netCharts":"*/20 * * * *",
                "netChartsNum":74,
                "shareCharts":"*/20 * * * *",
                "shareChartsNum":74
	},

	"upstreamCheckInterval": "5s",
	"upstream": [
		{
			"name": "main",
			"url": "http://127.0.0.1:8545",
			"timeout": "10s"
		},
		{
			"name": "backup",
			"url": "http://127.0.0.2:8545",
			"timeout": "10s"
		}
	],

	"redis": {
		"endpoint": "127.0.0.1:6379",
		"poolSize": 10,
		"database": 1,
		"password": ""
	},
  
	"exchange": {
		   "enabled": true,
		   "url": "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=ethereum-classic",
		   "timeout": "50s",
		   "refreshInterval": "900s"
    },

	"unlocker": {
		"enabled": true,
		"poolFee": 1.0,
		"poolFeeAddress": "",
		"depth": 120,
		"immatureDepth": 20,
		"keepTxFees": false,
		"interval": "10m",
		"daemon": "http://127.0.0.1:8545",
		"timeout": "10s"
	},

	"payouts": {
		"enabled": false,
		"requirePeers": 1,
		"interval": "20m",
		"daemon": "http://127.0.0.1:8545",
		"timeout": "10s",
		"address": "0xdb4166bC182595067e8392Df0f46FA9f4cc87524",
		"gas": "21000",
		"gasPrice": "50000000000",
		"autoGas": true,
		"threshold": 500000000,
		"bgsave": false,
		"concurrentTx": 10
	},

	"newrelicEnabled": false,
	"newrelicName": "MyEtherProxy",
	"newrelicKey": "SECRET_KEY",
	"newrelicVerbose": false
}

and further

https://github.com/yuriy0803/open-etc-pool-friends/blob/master/www/config/environment.js#L18 
https://github.com/yuriy0803/open-etc-pool-friends/blob/master/www/config/environment.js#L25  port: 8009
https://github.com/yuriy0803/open-etc-pool-friends/blob/master/www/config/environment.js#L44 port: 8081
./build.sh

## nginx

upstream api2 {
	server 127.0.0.1:8081;
}

server {
	listen 0.0.0.0:80;
	root /path/to/pool/www/dist;
	index index.html index.htm;

	server_name localhost;

	location /api2 {
		proxy_pass http://api2;
	}

	location / {
		try_files $uri $uri/ /index.html;
	}
}

sudo service nginx restart

cd open-etc-pool-friends

./build/bin/open-etc-pool-friends api.json

**Comment by jvxis** [comment]
Do you know why I need to change ports if it is a totally new server? new server, new geth, new wallet, new redis. I installed everything in a new server following your videos and the step by step here.

**Comment by yuriy0803** [comment]
new server Geth and pool on the same server
you just need to change wallet
=)




{
	"threads": 4,
	"coin": "etc",
	"name": "main",
        "pplns": 9000,
	"network": "classic",
	"coin-name":"etc",

	"proxy": {
		"enabled": true,
		"listen": "0.0.0.0:8888",
		"limitHeadersSize": 1024,
		"limitBodySize": 256,
		"behindReverseProxy": false,
		"blockRefreshInterval": "120ms",
		"stateUpdateInterval": "3s",
		"difficulty": 2000000000,
		"hashrateExpiration": "3h",

		"healthCheck": true,
		"debug": true,
		"maxFails": 100,

		"stratum": {
			"enabled": true,
			"listen": "0.0.0.0:8008",
			"maxConn": 8192,
			"tls": false,
                        "certFile": "/path/to/cert.pem",
                        "keyFile": "/path/to/key.pem"
		},

		"policy": {
			"workers": 8,
			"resetInterval": "60m",
			"refreshInterval": "1m",

			"banning": {
				"enabled": false,
				"ipset": "blacklist",
				"timeout": 1800,
				"invalidPercent": 30,
				"checkThreshold": 30,
				"malformedLimit": 5
			},
			"limits": {
				"enabled": false,
				"limit": 30,
				"grace": "5m",
				"limitJump": 10
			}
		}
	},

	"api": {
		"enabled": true,
		"purgeOnly": false,
		"purgeInterval": "10m",
		"listen": "0.0.0.0:8080",
		"statsCollectInterval": "5s",
		"hashrateWindow": "30m",
		"hashrateLargeWindow": "3h",
		"luckWindow": [64, 128, 256],
		"payments": 30,
		"blocks": 50,
		"poolCharts":"*/20 * * * *",
		"poolChartsNum":74,
		"minerCharts":"*/20 * * * *",
                "minerChartsNum":74,
                "netCharts":"*/20 * * * *",
                "netChartsNum":74,
                "shareCharts":"*/20 * * * *",
                "shareChartsNum":74
	},

	"upstreamCheckInterval": "5s",
	"upstream": [
		{
			"name": "main",
			"url": "http://127.0.0.1:8545",
			"timeout": "10s"
		},
		{
			"name": "backup",
			"url": "http://127.0.0.2:8545",
			"timeout": "10s"
		}
	],

	"redis": {
		"endpoint": "127.0.0.1:6379",
		"poolSize": 10,
		"database": 0,
		"password": ""
	},
  
	"exchange": {
		   "enabled": true,
		   "url": "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=ethereum-classic",
		   "timeout": "50s",
		   "refreshInterval": "900s"
    },

	"unlocker": {
		"enabled": true,
		"poolFee": 1.0,
		"poolFeeAddress": "",
		"depth": 120,
		"immatureDepth": 20,
		"keepTxFees": false,
		"interval": "10m",
		"daemon": "http://127.0.0.1:8545",
		"timeout": "10s"
	},

	"payouts": {
		"enabled": false,
		"requirePeers": 1,
		"interval": "20m",
		"daemon": "http://127.0.0.1:8545",
		"timeout": "10s",
		"address": "0xdb4166bC182595067e8392Df0f46FA9f4cc87524",
		"gas": "21000",
		"gasPrice": "50000000000",
		"autoGas": true,
		"threshold": 500000000,
		"bgsave": false,
		"concurrentTx": 10
	},

	"newrelicEnabled": false,
	"newrelicName": "MyEtherProxy",
	"newrelicKey": "SECRET_KEY",
	"newrelicVerbose": false
}

**Comment by yuriy0803** [comment]
is geth somewhere else
and wallet




"upstream": [
	{
		"name": "main",
		"url": "http://server geth ip:8545",
		"timeout": "10s"
	},
	{
		"name": "backup",
		"url": "http://server geth ip:8545",
		"timeout": "10s"
	}
],

"redis": {
	"endpoint": "127.0.0.1:6379",
	"poolSize": 10,
	"database": 0,
	"password": ""
},

"exchange": {
	   "enabled": true,
	   "url": "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=ethereum-classic",
	   "timeout": "50s",
	   "refreshInterval": "900s"
},

"unlocker": {
	"enabled": true,
	"poolFee": 1.0,
	"poolFeeAddress": "",
	"depth": 120,
	"immatureDepth": 20,
	"keepTxFees": false,
	"interval": "10m",
	"daemon": "http://server geth ip:8545",
	"timeout": "10s"
},

"payouts": {
	"enabled": false,
	"requirePeers": 1,
	"interval": "20m",
	"daemon": "http://server geth ip:8545",
	"timeout": "10s",
	"address": "0xdb4166bC182595067e8392Df0f46FA9f4cc87524",
	"gas": "21000",
	"gasPrice": "50000000000",
	"autoGas": true,
	"threshold": 500000000,
	"bgsave": false,
	"concurrentTx": 10
},

**Comment by yuriy0803** [comment]
but only old geth new server and pool new server

**Comment by yuriy0803** [comment]
usually a pool a geth
in the same server

**Comment by yuriy0803** [comment]
that means api.json standard you just need to change wallet

**Comment by yuriy0803** [comment]
otherwise everything will be complicated

**Comment by yuriy0803** [comment]
Then it should work

jvxis ***@***.***> schrieb am Mo., 15. Aug. 2022, 21:24:

**Comment by yuriy0803** [comment]
only you have to add new wallet
https://github.com/yuriy0803/open-etc-pool-friends/blob/master/api.json#L122
./build/bin/open-etc-pool-friends api.json

**Comment by yuriy0803** [comment]
then it should work

**Comment by yuriy0803** [comment]
I'm slowly getting confused myself 😅😅😅😅

**Comment by jvxis** [comment]
No problem @yuriy0803. I think the problem is here. It is the second time that I installed your pool, the first works perfectly, I don't know this one it is not working as I did the same. The only difference, is, that the first is a physical machine, and this one a virtual. I upgraded ubuntu, and I will try again.

**Comment by jvxis** [comment]
Everything new and the same error: 
panic: util: Can't parse duration ``: time: invalid duration ""
It seems to be a compilation problem. Maybe I need to compile the pool sw again.

**Comment by yuriy0803** [comment]
I always test before adding new code to Github

**Comment by jvxis** [comment]
I'm pretty sure about that, I think it is on my side.

**Comment by yuriy0803** [comment]
Senden Sie mir erneut api.json

**Comment by jvxis** [comment]
Sure. 
{
	"threads": 10,
	"coin": "etc",
	"name": "main",
        "pplns": 9000,
	"network": "classic",
	"coin-name":"etc",

	"proxy": {
		"enabled": true,
		"listen": "0.0.0.0:8888",
		"limitHeadersSize": 1024,
		"limitBodySize": 256,
		"behindReverseProxy": false,
		"blockRefreshInterval": "120ms",
		"stateUpdateInterval": "3s",
		"difficulty": 2000000000,
		"hashrateExpiration": "3h",

		"healthCheck": true,
		"debug": true,
		"maxFails": 100,

		"stratum": {
			"enabled": true,
			"listen": "0.0.0.0:8008",
			"maxConn": 8192,
			"tls": false,
                        "certFile": "/path/to/cert.pem",
                        "keyFile": "/path/to/key.pem"
		},

		"policy": {
			"workers": 8,
			"resetInterval": "60m",
			"refreshInterval": "1m",

			"banning": {
				"enabled": false,
				"ipset": "blacklist",
				"timeout": 1800,
				"invalidPercent": 30,
				"checkThreshold": 30,
				"malformedLimit": 5
			},
			"limits": {
				"enabled": false,
				"limit": 30,
				"grace": "5m",
				"limitJump": 10
			}
		}
	},

	"api": {
		"enabled": true,
		"purgeOnly": false,
		"purgeInterval": "10m",
		"listen": "0.0.0.0:8080",
		"statsCollectInterval": "5s",
		"hashrateWindow": "30m",
		"hashrateLargeWindow": "3h",
		"luckWindow": [64, 128, 256],
		"payments": 30,
		"blocks": 50,
		"poolCharts":"*/20 * * * *",
		"poolChartsNum":74,
		"minerCharts":"*/20 * * * *",
                "minerChartsNum":74,
                "netCharts":"*/20 * * * *",
                "netChartsNum":74,
                "shareCharts":"*/20 * * * *",
                "shareChartsNum":74
	},

	"upstreamCheckInterval": "5s",
	"upstream": [
		{
			"name": "main",
			"url": "http://127.0.0.1:8545",
			"timeout": "10s"
		},
		{
			"name": "backup",
			"url": "http://127.0.0.1:8545",
			"timeout": "10s"
		}
	],

	"redis": {
		"endpoint": "127.0.0.1:6379",
		"poolSize": 10,
		"database": 0,
		"password": ""
	},
  
	"exchange": {
		   "enabled": true,
		   "url": "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=ethereum-classic",
		   "timeout": "50s",
		   "refreshInterval": "900s"
    },

	"unlocker": {
		"enabled": false,
		"poolFee": 1.0,
		"poolFeeAddress": "",
		"depth": 120,
		"immatureDepth": 20,
		"keepTxFees": false,
		"interval": "10m",
		"daemon": "http://127.0.0.1:8545",
		"timeout": "10s"
	},

	"payouts": {
		"enabled": false,
		"requirePeers": 1,
		"interval": "20m",
		"daemon": "http://127.0.0.1:8545",
		"timeout": "10s",
		"address": "0xdb4166bC182595067e8392Df0f46FA9f4cc87524",
		"gas": "21000",
		"gasPrice": "50000000000",
		"autoGas": true,
		"threshold": 500000000,
		"bgsave": false,
		"concurrentTx": 10
	},

	"newrelicEnabled": false,
	"newrelicName": "MyEtherProxy",
	"newrelicKey": "SECRET_KEY",
	"newrelicVerbose": false
}

**Comment by yuriy0803** [comment]
Do you have a valid time zone in ubuntu?

**Comment by yuriy0803** [comment]
checked

**Comment by jvxis** [comment]
Yes. it ok. America Sao Paulo
![image](https://user-images.githubusercontent.com/108929149/184714123-8e664c7e-d313-4562-b098-b19a82c384a9.png)

**Comment by yuriy0803** [comment]
please send me teamviewer pa email i want to see it

**Comment by yuriy0803** [comment]
office.poolnode@gmail.com

**Comment by jvxis** [comment]
you should receive a team viewer invite.

**Comment by yuriy0803** [comment]
you id and pass   office.poolnode@gmail.com

**Comment by yuriy0803** [comment]
I found errors

**Comment by yuriy0803** [comment]
🤦‍♂️

**Comment by yuriy0803** [comment]
please add api.json
=)
https://github.com/yuriy0803/open-etc-pool-friends/commit/9130fb2cf228a60ec1910641521e81a63353cd4a

**Comment by jvxis** [comment]
let me check

**Comment by jvxis** [comment]
you nailed it! That's it. It is working now. Thanks man! I use the api.json that I download with the package.

**Comment by yuriy0803** [comment]
go to

# cd open-etc-pool-friends
and 
# git pull

**Comment by yuriy0803** [comment]
so you could update my pool

**Comment by yuriy0803** [comment]
in github it was my fault i accidentally deleted it i updated github now

**Comment by jvxis** [comment]
perfect. I will.

**Comment by jvxis** [comment]
version 22.04 ubuntu has a error with git. Now that I upgraded Ubuntu I'm getting this error. 
![image](https://user-images.githubusercontent.com/108929149/184726201-84a043c6-d2fa-4536-89bd-63cf6f1d7598.png)

**Comment by yuriy0803** [comment]
please look in google github errors

**Comment by yuriy0803** [comment]
https://github.com/Homebrew/linuxbrew-core/issues/20826

**Comment by jvxis** [comment]
yes, I tried all. What worked was a downgraded Ubuntu version. Unfortunately.

**Comment by yuriy0803** [comment]
version 22.04 works for me

**Comment by yuriy0803** [comment]
just try
sudo rm -r open-etc-pool-friends

**Comment by yuriy0803** [comment]
git clone https://github.com/yuriy0803/open-etc-pool-friends.git

**Comment by yuriy0803** [comment]
should work in future

**Comment by jvxis** [comment]
believe or not, I tried this. It didn't work. It is very unlikely.  It only worked downgraded Ubuntu to 20.04

**Comment by yuriy0803** [comment]
OK, it doesn't work for me either

**Comment by yuriy0803** [comment]
I just tested

**Comment by yuriy0803** [comment]
the problem is
So ändern Sie Informationen im Ubuntu-Pool

**Comment by yuriy0803** [comment]
that is normal

**Comment by yuriy0803** [comment]
The problem is if you change my github to linux you can't update it anymore

**Comment by yuriy0803** [comment]
that is normal

**Comment by yuriy0803** [comment]
She could download my codes differently and add them manually

**Comment by yuriy0803** [comment]
oder überprüfen Sie meine Geschichte selbst
or check my history yourself

https://github.com/yuriy0803/open-etc-pool-friends/commits/master

**Comment by yuriy0803** [comment]
here you can see what I change
