### ISSUE TITLE
core geth launch

### ISSUE THREAD

**Issue by feculay** [yuriy0803/open-etc-pool-friends#43]
query, what is the difference in setting core-geth to --syncmode "snap" and not "full", and why set it to --snapshots=false ?, according to your videos?

**Comment by yuriy0803** [comment]
https://etclabscore.github.io/core-geth/   Here you will find more information

**Comment by feculay** [comment]
I did not find an answer, would you be so kind to make a little explanation?  Thank you

**Comment by yuriy0803** [comment]
https://geth.ethereum.org/docs/faq

**Comment by yuriy0803** [comment]
https://github.com/ethereum/go-ethereum/issues/23075

**Comment by yuriy0803** [comment]
--snapshot                                Enables snapshot-database mode (default = enable)
