### ISSUE TITLE
upstreams api

### ISSUE THREAD

**Issue by feculay** [yuriy0803/open-etc-pool-friends#44]
another query, if i only have one core-geth daemon running
Why should I have a backup here? What does it do? why 127.0.0.2?, they are queries to be able to understand, and not make mistakes, thanks

  "upstream": [
    {
      "name": "main",
      "url": "http://127.0.0.1:8545",
      "timeout": "10s"
    },
    {
      "name": "backup",
      "url": "http://127.0.0.2:8545",
      "timeout": "10s"
    }
  ],

**Comment by yuriy0803** [comment]
It's just API information
