### ISSUE TITLE
Cloudflare stratum

### ISSUE THREAD

**Issue by feculay** [yuriy0803/open-etc-pool-friends#45]
Do you know how to configure the stratum port to serve through cloudflare?

Set to true if you are behind CloudFlare (not recommended) or behind http-reverse
      proxy to enable IP detection from X-Forwarded-For header.
      Advanced users only. It's tricky to make it right and secure.
    */
    "behindReverseProxy": false

**Comment by yuriy0803** [comment]
new-subdomain
for ports
but without proxy connection
