### ISSUE TITLE
How to create public api

### ISSUE THREAD

**Issue by feculay** [yuriy0803/open-etc-pool-friends#46]
Hi, how to create public api of pool for send for example to mininpoolstats?

**Comment by MiningCryptoLive** [comment]
> Hi, how to create public api of pool for send for example to mininpoolstats?

1st please do not open as an issue. This has nothing to do with the pool code. 

Second. All you have to do is submit your site to miningpoolstats and they will pull the API info.

The API is already public unless you are running the pool on localhost. In that case you need to run the pool publicly

**Comment by feculay** [comment]
Thanks, sorry
