### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by argenpool** [yuriy0803/open-etc-pool-friends#47]
Hi, i dont know if this is a good place to post this, I've already an old setup of this pool working great at argenpool.org. My concerns are about these new updates u do yesterday. I've cloned and build succesfully, but when i run get this error : 
"  ./open-etc-pool-friends api.json
2022/09/07 01:51:49 Loading config: /home/pool/open-etc-pool-friends/build/bin/api.json
2022/09/07 01:51:49 Running with 2 threads
2022/09/07 01:51:49 Backend check reply: PONG
2022/09/07 01:51:49 Starting API on 0.0.0.0:8080
2022/09/07 01:51:49 Set Exchange data refresh every 15m0s
2022/09/07 01:51:49 Set stats collect interval to 5s
2022/09/07 01:51:49 Set purge interval to 10m0s
2022/09/07 01:51:49 &{GET https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=ethereum-classic HTTP/1.1 1 1 map[Accept:[application/json] Content-Type:[application/json]] <nil> <nil> 0 [] false api.coingecko.com map[] map[] <nil> map[]   <nil> <nil> <nil> 0xc0000c4078}
2022/09/07 01:51:49 Purged stale stats from backend, 0 shares affected, elapsed time 402.809µs
panic: runtime error: index out of range [9] with length 9

goroutine 21 [running]:
github.com/yuriy0803/open-etc-pool-friends/storage.convertBlockResults(0xc00006fe50, 0x1, 0x1, 0xd, 0xc0000d7988, 0x0)
        /home/pool/open-etc-pool-friends/build/_workspace/src/github.com/yuriy0803/open-etc-pool-friends/storage/redis.go:1499 +0x885
github.com/yuriy0803/open-etc-pool-friends/storage.(*RedisClient).CollectStats(0xc0000adbf0, 0x1a3185c5000, 0x32, 0x1e, 0x0, 0x0, 0x0)
        /home/pool/open-etc-pool-friends/build/_workspace/src/github.com/yuriy0803/open-etc-pool-friends/storage/redis.go:1149 +0x650
github.com/yuriy0803/open-etc-pool-friends/api.(*ApiServer).collectStats(0xc000088060)
        /home/pool/open-etc-pool-friends/build/_workspace/src/github.com/yuriy0803/open-etc-pool-friends/api/server.go:261 +0x8a
github.com/yuriy0803/open-etc-pool-friends/api.(*ApiServer).Start(0xc000088060)
        /home/pool/open-etc-pool-friends/build/_workspace/src/github.com/yuriy0803/open-etc-pool-friends/api/server.go:91 +0x2b0
main.startApi()
        /home/pool/open-etc-pool-friends/build/_workspace/src/github.com/yuriy0803/open-etc-pool-friends/main.go:33 +0x47
created by main.main
        /home/pool/open-etc-pool-friends/build/_workspace/src/github.com/yuriy0803/open-etc-pool-friends/main.go:103 +0x25f"
        
       My goal are to introduce these newer features like 'earn per day' to my project.. It's possible to add these features to production without cloning the repo again? 
       Thanks in advance

**Comment by yuriy0803** [comment]
If you want to update new ones you have to clean (redis).

**Comment by argenpool** [comment]
do u mean 
       redis-cli KEYS "etc*" | xargs redis-cli DEL

**Comment by argenpool** [comment]
Thanks, worked
