### ISSUE TITLE
error when make

### ISSUE THREAD

**Issue by cristianvsl** [yuriy0803/open-etc-pool-friends#48]
# github.com/etclabscore/core-geth/common
../../etclabscore/core-geth/common/test_utils.go:27:18: undefined: os.ReadFile
# github.com/ethereum/go-ethereum/common
../../ethereum/go-ethereum/common/test_utils.go:27:18: undefined: os.ReadFile
# golang.org/x/sys/unix
../../../golang.org/x/sys/unix/syscall.go:83:16: undefined: unsafe.Slice
../../../golang.org/x/sys/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
../../../golang.org/x/sys/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
make: *** [Makefile:12: all] Error 2

Was working fine few days ago. What happend? I tried with node 8.17.0 and 10.24.1 with go 1.13 (sudo apt install golang-go). With node v10.24.1 and go13 was working untill about few days ago!

Sorted with go1.17.13

Can be closed

**Comment by MiningCryptoLive** [comment]
Update go to 1.17

**Comment by yuriy0803** [comment]
https://github.com/yuriy0803/open-etc-pool-friends/commit/35061687ddf42328ce646330fb3cc95e69f86f62

**Comment by yuriy0803** [comment]
1...     make clean all
2...  make

**Comment by cristianvsl** [comment]
http://etc.mining-pub.com :)
