### ISSUE TITLE
SSL Frontend

### ISSUE THREAD

**Issue by cristianvsl** [yuriy0803/open-etc-pool-friends#49]
Any of you know how to setup nginx for SSL ? I have managed to get it working once but i completely forgot how i did it.

**Comment by MiningCryptoLive** [comment]
sudo certbot --nginx -d <your-pool-domain>

**Comment by cristianvsl** [comment]
I doubt that will also setup the ssl block or the 80 block for nginx along with the 301 for redirecting 80 to ssl. I have ssl certs for production but i am stuck at building the nginx blocks for ssl

**Comment by MiningCryptoLive** [comment]
> I doubt that will also setup the ssl block or the 80 block for nginx along with the 301 for redirecting 80 to ssl. I have ssl certs for production but i am stuck at building the nginx blocks for ssl

If you follow the instructions above it will walk you through it. It will ask for your email to notify when you need to renew the ssl. It will ask you if you want to redirect all traffic to ssl and create the server blocks

**Comment by cristianvsl** [comment]
okay i`ll git it a try. thank you

**Comment by cristianvsl** [comment]
MiningCryptoLive Thank you for the help. It worked
If anyone looks for doing this here is the up to date on how to:

$ sudo add-apt-repository -r ppa:certbot/certbot
$ sudo apt-get update
$ sudo apt-get install python3-certbot-nginx
$ sudo certbot --nginx -d your_domain

**Comment by argenpool** [comment]
I followed these steps but got an API inactive message.
Any suggestions what I'm doing wrong?

**Comment by feculay** [comment]
https://certbot.eff.org/
