### ISSUE TITLE
pool etc,callisto, ubiq, etica in some pool 

### ISSUE THREAD

**Issue by feculay** [yuriy0803/open-etc-pool-friends#52]
Hello, I have installed callisto and ethics before enabling it, it is in production, how can I modify the code to create ethica and callisto pool, without reinstalling everything?, thanks

**Comment by yuriy0803** [comment]
https://github.com/yuriy0803/open-etc-pool-friends/blob/master/api.json#L6

 "network": "callisto",

"database": 1,


https://github.com/yuriy0803/open-etc-pool-friends/blob/master/api.json#L96

**Comment by feculay** [comment]
I understand what you are telling me, but the question is: I have installed the version from a month ago, how do I modify the codes changed by you until today, without doing "make" again especially open-etc-pool-friends, and thus be able to create pool of callisto and ethics?

**Comment by yuriy0803** [comment]
git pull
make clean all

**Comment by feculay** [comment]
> git pull
> make clean all

what you indicate, does not modify or affect the Pool that is running from etc?
