### ISSUE TITLE
No block on pool - lost?

### ISSUE THREAD

**Issue by galiy** [yuriy0803/open-etc-pool-friends#60]
Привет! У меня пул не поймал ни одного блока за несколько дней хотя мощности вроде бы достаточно.
В ЛОГе есть сообщения:
Hello! My pool did not find a block for several days, although the power seems to be enough.
There are messages in the LOG:
...
2023/03/10 00:00:38 share difficulty too low, -24996.657698 < 1618693980288798, from 0x...
2023/03/10 02:27:01 share difficulty too low, -27032.722988 < 1627925428612743, from 0x
2023/03/10 05:09:16 share difficulty too low, -21996.905202 < 1643585209814743, from 0x
2023/03/10 05:40:51 share difficulty too low, -31703.904693 < 1633109497669266, from 0x
2023/03/10 13:43:47 share difficulty too low, -1918.558293 < 1591309932208405, from 0x
...
Не могут ли это быть "потерянные" блоки из-за какой-то недоработки в процедуре проверки? Возможно переполнение целочисленного значения?
Could these be "lost" blocks due to some flaw in the verification procedure? Maybe integer overflow?

**Comment by galiy** [comment]
How share diff may be < 0 ?

**Comment by galiy** [comment]
I Build debug version
2023/03/10 17:48:42 E-Difficulty pool/block/share = 16000000000 / 1586228021217913 / 164156975815360(-27315.808863) from 0x...
2023/03/10 17:48:42 E-share difficulty too low, -27315.808863 < 1586228021217913, from 0x...
Hi diff  negative result
Block diff be negative too?

**Comment by galiy** [comment]
sample code on https://go.dev/play/p/tdmZlpb8yUf?v=goprev


```
package main

import (
	"fmt"

	"github.com/yuriy0803/open-etc-pool-friends/util"
)

func main() {
	shareDiff := 16000000000
	Difficulty := 1586228021217913
	var shareDiffCalc int64 = 1641569758153600
	shareDiffFloat := util.DiffIntToFloat(shareDiffCalc)
	fmt.Printf("E-Difficulty pool/block/share = %d / %d / %d(%f) \n", shareDiff, Difficulty, shareDiffCalc, shareDiffFloat)
}

```

**Comment by yuriy0803** [comment]
hello what you are trying will not work

so you can simply convert


package main

import (
	"fmt"
	"math"
)

func main() {
	// Number of hashes
	hashes := 123456789

	// Elapsed time in seconds
	elapsed := 60.0

	// Calculate hashrate
	hashrate := float64(hashes) / elapsed

	// Calculate hashrate unit
	i := int(math.Log10(hashrate) / 3)
	unit := []string{"H/s", "KH/s", "MH/s", "GH/s", "TH/s", "PH/s"}[i]

	// Format hashrate with unit
	hashrateFormatted := hashrate / math.Pow(1000, float64(i))

	// Print hashrate with unit
	fmt.Printf("Hashrate: %.2f %s", hashrateFormatted, unit)
}
 


https://go.dev/play/p/37jCEGIIT5N

**Comment by yuriy0803** [comment]
package main

import (
	"fmt"
)

var units = []string{"H/s", "KH/s", "MH/s", "GH/s", "TH/s", "PH/s"}

func formatHashrate(hashrate float64) string {
	i := 0
	for hashrate > 1000 {
		hashrate = hashrate / 1000
		i++
	}
	return fmt.Sprintf("%.2f %s", hashrate, units[i])
}

func main() {
	// Example usage
	hashrate := 105311309967.0
	formattedHashrate := formatHashrate(hashrate)
	fmt.Println(formattedHashrate)
}




https://go.dev/play/p/JLJEtjWvmk8

**Comment by galiy** [comment]
You don't understand me... I test you pool "open-etc-pool-friends" and nave errors "share difficulty too low" with big negative values. It my be blocks, share hashrate > network diiff, but pool trash share.

**Comment by galiy** [comment]
Strange. I spoke about /proxy/miner.go func  processShare
Line 80 (I commented several lines)
![image](https://user-images.githubusercontent.com/23344960/224455673-7d86279d-80be-4465-b140-d6ffff288bb8.png)
