### ISSUE TITLE
How to support Antminer E9 Pro

### ISSUE THREAD

**Issue by luckchn** [yuriy0803/open-etc-pool-friends#62]
How to support Antminer E9 Pro?

**Comment by yuriy0803** [comment]
Hello I guess so
You can try my pool

https://miningpoolstats.stream/yu-tam.contact_pools

**Comment by luckchn** [comment]
I tried it, but I can't connect, and the error message is ”unsupported stratum version“

**Comment by yuriy0803** [comment]
ethproxy
https://github.com/yuriy0803/open-etc-pool-friends/blob/master/docs/STRATUM.md
and 

Ethereum stratum mining protocol v1.0.0

https://github.com/yuriy0803/open-etc-pool-friends/blob/master/EthereumStratum_NiceHash_v1.0.0.txt

**Comment by yuriy0803** [comment]
'365b42025dec9', /// 13 Number of letters and number
'ee6f5a28e595fefe3733959956d9faff18b3098e98fd901ee8f54f8791cfb1c2',     /// 64 Number of letters and number
'30f28598ab6eacb2da0067c482b80999f27cf9c092399be7b08370f7df08c346',    ///  64 Number of letters and number

**Comment by yuriy0803** [comment]
https://github.com/yuriy0803/open-etc-pool-friends/commit/c2d9c33000c2eb2bc08b586e09a385bdb726cde0

hello can you test please

**Comment by luckchn** [comment]
please wait a momenti'll do the test after 20:00 utc+8

**Comment by luckchn** [comment]
can't
the chip is heating but no work submitted
the e9p web page display :
normal
![normal](https://user-images.githubusercontent.com/30102946/236671067-717b2d09-f078-400d-a48b-547e799664bb.PNG)
abnormal
![abnormal](https://user-images.githubusercontent.com/30102946/236671082-019f3fc7-b81b-4af3-8176-e8b769923c16.PNG)

**Comment by yuriy0803** [comment]
how do i understand that
So it works and you have a cheaper share

**Comment by yuriy0803** [comment]
I wrote that it works.
