### ISSUE TITLE
Build web interface ubuntu 20.04 server

### ISSUE THREAD

**Issue by says112** [yuriy0803/open-etc-pool-friends#66]
![Снимок экрана (92)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/5d8ad83b-208a-41af-8c0c-d6340778d592)
Hello! I'm trying to build your pool but I can't build a web interface, tell me what's the problem?
![Снимок экрана (91)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/58f2e049-fbd0-4840-a7e2-78261ec8c067)

**Comment by yuriy0803** [comment]
User 
sudo chown -R alex:alex ~/.npm
 sudo chown -R alex:alex ~/.config
 npm install
 bower install

**Comment by says112** [comment]
> 

![Uploading Снимок экрана (93).png…]()

**Comment by says112** [comment]
> Пользователь sudo chown -R alex:alex ~/.npm sudo chown -R alex:alex ~/.config npm install bower install

![Снимок экрана (93)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/6ab4f8ec-6a80-4554-9dc3-b5ea0cee2551)

**Comment by yuriy0803** [comment]
When I have time, I look it up on the /www

**Comment by says112** [comment]
Tell me what are the errors?
![Снимок экрана (114)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/bd925b00-35fc-476b-bef8-21ec2c8553b3)
