### ISSUE TITLE
White page of the web interface!

### ISSUE THREAD

**Issue by says112** [yuriy0803/open-etc-pool-friends#67]
White page of the web interface!
![Снимок экрана (125)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/6b4a04f5-8ba5-4153-b9bf-0140fabd3a23)

**Comment by says112** [comment]
Hello! Please tell me I installed your pool but the statistics on it do not work correctly how to fix the error?
![Снимок экрана (131)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/79a5268c-dd72-455a-97eb-eae0746cce48)

**Comment by yuriy0803** [comment]
Hello I think you have to wait until geth is ready

**Comment by says112** [comment]
{
	"threads": 4,
	"coin": "cau",
	"name": "main",
    "pplns": 9000,
	"network": "ethereum",
	"algo": "ethash",
	"coin-name":"",

	"proxy": {
		"enabled": true,
		"listen": "0.0.0.0:8888",
		"limitHeadersSize": 1024,
		"limitBodySize": 256,
		"behindReverseProxy": false,
		"blockRefreshInterval": "120ms",
		"stateUpdateInterval": "3s",
		"difficulty": 1000000000,
		"hashrateExpiration": "3h",

		"healthCheck": true,
		"debug": true,
		"maxFails": 100,

		"stratum": {
			"enabled": true,
			"listen": "0.0.0.0:8008",
			"timeout": "120s",
			"maxConn": 8192,
			"tls": false,
                        "certFile": "/path/to/cert.pem",
                        "keyFile": "/path/to/key.pem"
		},

		"policy": {
			"workers": 8,
			"resetInterval": "60m",
			"refreshInterval": "1m",
			"blacklist_file" : "/home/pool/open-etc-pool-friends/stratum_blacklist.json",

			"banning": {
				"enabled": false,
				"ipset": "blacklist",
				"timeout": 1800,
				"invalidPercent": 30,
				"checkThreshold": 30,
				"malformedLimit": 5
			},
			"limits": {
				"enabled": false,
				"limit": 30,
				"grace": "5m",
				"limitJump": 10
			}
		}
	},

	"api": {
		"enabled": true,
		"purgeOnly": false,
		"purgeInterval": "10m",
		"listen": "0.0.0.0:8080",
		"statsCollectInterval": "5s",
		"hashrateWindow": "30m",
		"hashrateLargeWindow": "3h",
		"luckWindow": [64, 128, 256],
		"payments": 30,
		"blocks": 50,
		"poolCharts":"0 */20 * * * *",
		"poolChartsNum":74,
		"minerCharts":"0 */20 * * * *",
                "minerChartsNum":74,
                "netCharts":"0 */20 * * * *",
                "netChartsNum":74,
                "shareCharts":"0 */20 * * * *",
                "shareChartsNum":74
	},

	"upstreamCheckInterval": "5s",
	"upstream": [
		{
			"name": "main",
			"url": "http://127.0.0.1:8545",
			"timeout": "10s"
		},
		{
			"name": "backup",
			"url": "http://127.0.0.2:8545",
			"timeout": "10s"
		}
	],

	"redis": {
		"endpoint": "127.0.0.1:6379",
		"poolSize": 10,
		"database": 0,
		"password": "",
                "sentinelEnabled": false,
                "masterName": "mymaster",
                "sentinelAddrs": [
            		"127.0.0.1:26379",
           	        "127.0.0.1:26389",
           	        "127.0.0.1:26399"
        ]
	},
  
	"exchange": {
		   "enabled": true,
		   "url": "",
		   "timeout": "50s",
		   "refreshInterval": "900s"
    },

	"unlocker": {
		"enabled": true,
		"poolFee": 1.0,
		"poolFeeAddress": "",
		"depth": 120,
		"immatureDepth": 20,
		"keepTxFees": false,
		"interval": "10m",
		"daemon": "http://127.0.0.1:8545",
		"timeout": "10s"
	},

	"payouts": {
		"enabled": false,
		"requirePeers": 1,
		"interval": "20m",
		"daemon": "http://127.0.0.1:8545",
		"timeout": "10s",
		"address": "0xB29E173CE8BFfFc03e1C28E4d2b3Dca9c296b81A",
		"gas": "21000",
		"gasPrice": "50000000000",
		"autoGas": true,
		"threshold": 500000000,
		"bgsave": false,
		"concurrentTx": 10
	},

	"newrelicEnabled": false,
	"newrelicName": "MyEtherProxy",
	"newrelicKey": "SECRET_KEY",
	"newrelicVerbose": false
}



Can you tell me the correct config file?

**Comment by says112** [comment]
Where can I edit block rewards?

**Comment by yuriy0803** [comment]
What kind of coin is that?

**Comment by says112** [comment]
canxium         
https://github.com/canxium/go-canxium

**Comment by yuriy0803** [comment]
Ethash

**Comment by says112** [comment]
YES

**Comment by yuriy0803** [comment]
Api.json
"network": "universal",

**Comment by yuriy0803** [comment]
https://github.com/yuriy0803/open-etc-pool-friends/blob/master/payouts/unlocker.go#L41
https://github.com/yuriy0803/open-etc-pool-friends/blob/master/payouts/unlocker.go#L42

go build 
And restart api.json

**Comment by yuriy0803** [comment]
This is how you can manually change block reward and uncle

**Comment by says112** [comment]
Yes?
![Снимок экрана (134)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/6278532d-fafb-46a2-be18-2c280f20bac0)
![Снимок экрана (135)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/669cdc55-31b1-4190-960f-099321e94f80)

**Comment by says112** [comment]
What are these blocks? They are not in the wallet.
![Снимок экрана (137)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/4dd095ae-7e18-46bc-a2db-c8b873819744)

**Comment by yuriy0803** [comment]
You have to wait for geth node to finish sync

**Comment by yuriy0803** [comment]
Your geth is not ready yet

**Comment by says112** [comment]
Thank you OK!

**Comment by says112** [comment]
Miner must be enabled?

**Comment by says112** [comment]
Still not synchronized and the hashrate is decreasing.
![Снимок экрана (138)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/465170d0-dc60-4286-bc4a-5e87ac93fea7)
