### ISSUE TITLE
 The pool is not connected to the mining network.

### ISSUE THREAD

**Issue by says112** [yuriy0803/open-etc-pool-friends#68]
Hello! The pool did not work, it does not see the main caunxium network.
![Снимок экрана (140)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/5fc4d400-c0cc-4e8e-a8de-c6b72d30f8d8)

**Comment by jeje0106** [comment]
Hi,

Did you apply Genesis of Canxium before starting geth?

This is available here:

https://github.com/canxium/go-canxium/tree/main/genesis

If you haven't applied it, you need to delete the .canxium directory and start over (don't forget to recover your keystore)

Best Regards,

**Comment by says112** [comment]
![Снимок экрана (146)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/8e927616-ebac-4a73-b89b-bb2d821f113b)

**Comment by jeje0106** [comment]
Choose etica network by modifying the reward accordingly. And go build

**Comment by jeje0106** [comment]
Change Universal in api by etica

**Comment by says112** [comment]
Works! Tell me how to find out which network should be registered in the settings?
![Снимок экрана (148)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/16b2dc38-214b-48a3-b8bc-9d33c28eef5c)

**Comment by jeje0106** [comment]
Hi,

There:

https://github.com/yuriy0803/open-etc-pool-friends/blob/master/payouts/unlocker.go

func NewBlockUnlocker(cfg *UnlockerConfig, backend *storage.RedisClient, network string) *BlockUnlocker {
	// determine which monetary policy to use based on network
	// configure any reward params if needed.
	if network == "classic" {
		cfg.Ecip1017FBlock = 5000000
		cfg.Ecip1017EraRounds = big.NewInt(5000000)
	} else if network == "mordor" {
		cfg.Ecip1017FBlock = 0
		cfg.Ecip1017EraRounds = big.NewInt(2000000)
	} else if network == "ethereum" {
		cfg.ByzantiumFBlock = big.NewInt(4370000)
		cfg.ConstantinopleFBlock = big.NewInt(7280000)
	} else if network == "ethereumPow" {
		// nothing needs configuring here, simply proceed.
	} else if network == "ethereumFair" {
		cfg.ByzantiumFBlock = big.NewInt(4370000)
		cfg.ConstantinopleFBlock = big.NewInt(7280000)
	} else if network == "ropsten" {
		cfg.ByzantiumFBlock = big.NewInt(1700000)
		cfg.ConstantinopleFBlock = big.NewInt(4230000)
	} else if network == "expanse" {
		// nothing needs configuring here, simply proceed.
	} else if network == "etica" {
		// nothing needs configuring here, simply proceed.
	} else if network == "callisto" {
		// nothing needs configuring here, simply proceed.
	} else if network == "ubiq" {
		// nothing needs configuring here, simply proceed.
	} else if network == "octaspace" {
		// nothing needs configuring here, simply proceed.
	} else if network == "universal" {
		// nothing needs configuring here, simply proceed.
	} else {
		log.Fatalln("Invalid network set", network)
	}


Did you modify this?: 

// etica
func getConstRewardetica(height int64) *big.Int {
	// Rewards)
	// etica
	return calcBigNumber(2.0)

By:


// etica
func getConstRewardetica(height int64) *big.Int {
	// Rewards)
	// etica
	return calcBigNumber(0.1875)

Best Regards,

**Comment by jeje0106** [comment]
Be careful, the Uncle block with canxium is 0.

You must also modify this info in the file in etcia network like this:

``func getUncleReward(uHeight *big.Int, height *big.Int, reward *big.Int) *big.Int {
    r := big.NewInt(0)
    return r
}``


Zero is very important.

When you are done modifying the unlocker.go, go build and restart the pool.
