### ISSUE TITLE
redis DB going to big

### ISSUE THREAD

**Issue by reb0rn21** [yuriy0803/open-etc-pool-friends#70]
My redis DB after a month is 400Mb I see most redis key are set to expirity to TTL -1
Is there some option I missed which would set some inflated data keys to expire?

**Comment by reb0rn21** [comment]
Its just in a 30 days with ~30 miners redis DB is 400MB

**Comment by yuriy0803** [comment]
It's okay How else are you going to verify information

**Comment by reb0rn21** [comment]
Pool do not need to keep data from past 2+ weeks on each share, if it does I need to clean DB each few months when it reach 1+ GB
