### ISSUE TITLE
Can't see network.

### ISSUE THREAD

**Issue by says112** [yuriy0803/open-etc-pool-friends#74]
![Снимок экрана (194)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/36f57c2b-cad0-4a55-805d-249cd0f0d983)
Hello! Here, as I understand it, the port of the coin is the same as the default one? I did not change it, please tell me what other ports to look at?
![Снимок экрана (192)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/cfd2c00c-e9b7-4101-a0ef-e0398fab8e73)

**Comment by yuriy0803** [comment]
--http.port "8545"
