### ISSUE TITLE
 The pool does not see the network.

### ISSUE THREAD

**Issue by says112** [yuriy0803/open-etc-pool-friends#75]
Please see where the error is.

{
	"threads": 4,
	"coin": "pwr",
	"name": "main",
    "pplns": 9000,
	"network": "universal",
	"algo": "ethash",
	"coin-name":"pwr",

	"proxy": {
		"enabled": true,
		"listen": "0.0.0.0:8888",
		"limitHeadersSize": 1024,
		"limitBodySize": 256,
		"behindReverseProxy": false,
		"blockRefreshInterval": "120ms",
		"stateUpdateInterval": "3s",
		"difficulty": 1000000000,
		"hashrateExpiration": "3h",

		"healthCheck": true,
		"debug": true,
		"maxFails": 100,

		"stratum": {
			"enabled": true,
			"listen": "0.0.0.0:8008",
			"timeout": "120s",
			"maxConn": 8192,
			"tls": false,
                        "certFile": "/path/to/cert.pem",
                        "keyFile": "/path/to/key.pem"
		},

		"policy": {
			"workers": 8,
			"resetInterval": "60m",
			"refreshInterval": "1m",
			"blacklist_file" : "/home/pool/open-etc-pool-friends/stratum_blacklist.json",

			"banning": {
				"enabled": false,
				"ipset": "blacklist",
				"timeout": 1800,
				"invalidPercent": 30,
				"checkThreshold": 30,
				"malformedLimit": 5
			},
			"limits": {
				"enabled": false,
				"limit": 30,
				"grace": "5m",
				"limitJump": 10
			}
		}
	},

	"api": {
		"enabled": true,
		"purgeOnly": false,
		"purgeInterval": "10m",
		"listen": "0.0.0.0:8080",
		"statsCollectInterval": "5s",
		"hashrateWindow": "30m",
		"hashrateLargeWindow": "3h",
		"luckWindow": [64, 128, 256],
		"payments": 30,
		"blocks": 50,
		"poolCharts":"0 */20 * * * *",
		"poolChartsNum":74,
		"minerCharts":"0 */20 * * * *",
                "minerChartsNum":74,
                "netCharts":"0 */20 * * * *",
                "netChartsNum":74,
                "shareCharts":"0 */20 * * * *",
                "shareChartsNum":74
	},

	"upstreamCheckInterval": "5s",
	"upstream": [
		{
			"name": "main",
			"url": "http://127.0.0.1:8545",
			"timeout": "10s"
		},
		{
			"name": "backup",
			"url": "http://127.0.0.2:8545",
			"timeout": "10s"
		}
	],

	"redis": {
		"endpoint": "127.0.0.1:6379",
		"poolSize": 10,
		"database": 0,
		"password": "",
                "sentinelEnabled": false,
                "masterName": "mymaster",
                "sentinelAddrs": [
            		"127.0.0.1:26379",
           	        "127.0.0.1:26389",
           	        "127.0.0.1:26399"
        ]
	},
  
	"exchange": {
		   "enabled": true,
		   "url": "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=ethereum-classic",
		   "timeout": "50s",
		   "refreshInterval": "900s"
    },

	"unlocker": {
		"enabled": true,
		"poolFee": 1.0,
		"poolFeeAddress": "",
		"depth": 120,
		"immatureDepth": 20,
		"keepTxFees": false,
		"interval": "10m",
		"daemon": "http://127.0.0.1:8545",
		"timeout": "10s"
	},

	"payouts": {
		"enabled": false,
		"requirePeers": 1,
		"interval": "20m",
		"daemon": "http://127.0.0.1:8545",
		"timeout": "10s",
		"address": "0xB29E173CE8BFfFc03e1C28E4d2b3Dca9c296b81A",
		"gas": "21000",
		"gasPrice": "50000000000",
		"autoGas": true,
		"threshold": 500000000,
		"bgsave": false,
		"concurrentTx": 10
	},

	"newrelicEnabled": false,
	"newrelicName": "MyEtherProxy",
	"newrelicKey": "SECRET_KEY",
	"newrelicVerbose": false
}

**Comment by yuriy0803** [comment]
You have to wait until geth is ready send me geth log file foto

**Comment by says112** [comment]
I understand that pH is probably only 80% synchronized?
![Снимок экрана (195)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/12db3f78-c276-42bd-a08d-eadbd281b3c7)

**Comment by yuriy0803** [comment]
Is not finished wait until finished

**Comment by says112** [comment]
Thank you

**Comment by says112** [comment]
Can you please tell me how to find out what mark is needed for a coin? "network": "universal",

**Comment by yuriy0803** [comment]
https://github.com/yuriy0803/open-etc-pool-friends/blob/master/payouts/unlocker.gohttps://github.com/yuriy0803/open-etc-pool-friends/blob/master/payouts/unlocker.go

**Comment by yuriy0803** [comment]
it's a question of which block has reward
