### ISSUE TITLE
The pool is not going.

### ISSUE THREAD

**Issue by says112** [yuriy0803/open-etc-pool-friends#90]
![Снимок экрана (371)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/b5828f14-5748-46f4-9f8a-02166e004075)

The pool is not going.

**Comment by yuriy0803** [comment]
go env -w GO111MODULE=on

**Comment by says112** [comment]
OK! For OCTA SPACE network universal?

**Comment by says112** [comment]
![Снимок экрана (372)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/49ad7740-090f-4e8b-936f-b522fcc9f4a1)
Some kind of error came out when assembling the web interface.

**Comment by yuriy0803** [comment]
cd open-etc-pool-friends
bash install.sh

**Comment by says112** [comment]
![Снимок экрана (373)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/ac735eea-a95f-4495-8dd9-5b5f3d990202)

**Comment by yuriy0803** [comment]
https://github.com/yuriy0803/open-etc-pool-friends/blob/master/install.sh

**Comment by says112** [comment]
![Снимок экрана (374)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/a1961e48-115c-4025-91d5-48c217a2d651)

**Comment by says112** [comment]
![Uploading Снимок экрана (376).png…]()

**Comment by says112** [comment]
![Снимок экрана (380)](https://github.com/yuriy0803/open-etc-pool-friends/assets/22127398/e7ae150a-9bb1-4325-bb89-13837434b474)
